INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Organization', null, null, null, null, -1);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Avinya Board of Directors', 'foundation-bod', 'team', null, null, 12000);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Avinya Foundation', 'foundation', 'team', 'executive', null, 10000);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Technology Team, Curriculum Team, Operations Team', 'foundation-team', 'team', 'executive', '*', 9000);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Avinya Academies', 'avinya-academies', 'team', null, null, 4000);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Avinya Academy - Bandaragama', 'avinya-single-academy', 'team', null, null, 3000);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('AA Bandaragama - Educators, Bootcamp Program, Vocational Program(s)', 'academy-team', 'team', 'academic', null, 2000);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Person', null, null, null, null, -1);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Bootcamp Teacher Job Applicant', 'bootcamp-job-applicant', 'applicant', 'academic', 'empower', 0);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Bootcamp Applicant', 'student-applicant', 'applicant', 'student', 'empower', 0);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('* Student', 'student', 'customer', 'student', '*', 500);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Parent of Bootcamp Applicant', 'parent-applicant', 'applicant', 'parent', 'empower', 0);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Parent of * Student', 'parent-of-student', 'customer', 'parent', '*', 500);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Foundation-Level Employee', 'foundation-employee', 'employee', 'executive', null, 8500);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Bootcamp Teacher', 'bootcamp-teacher', 'employee', 'academic', 'empower', 1500);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Campus Lead', 'academy-staff', 'employee', 'staff', 'operations', 2500);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Campus Operations Associate', 'academy-operations-associate', 'employee', 'staff', 'operations', 1500);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Vocational Teacher (IT/Healthcare/Hospitality)', 'vocational-teacher', 'employee', 'academic', '(IT/Healthcare/Hospitality)', 1500);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Lakshman', 'sinhala-communicator', 'consultant', 'executive', 'marketing', 4500);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Dan', 'architect', 'consultant', 'executive', null, 4500);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Sampath', 'architect-prospect', 'volunteer', 'executive', null, 3500);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Rukmal', 'consultant-tech', 'consultant', 'executive', 'technology', 8500);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Samisa', 'cto', 'employee', 'executive', 'technology', 9500);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Dee', 'bootcamp-head', 'employee', 'executive', 'empower', 9500);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Anju', 'ed', 'employee', 'executive', null, 10500);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Jivaka', 'cfo-advisor', 'consultant', 'executive', 'finance', 9500);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Sanjiva', 'board-chairman', 'director', 'executive', null, 11500);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Mrs. Fernando', 'advisory-board-member', 'advisor', 'executive', null, 10500);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Software Engineer 1', 'foundation-software-engineers', 'employee', 'executive', 'technology', 4500);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Software Engineering Intern', 'foundation-software-interns', 'employee', 'executive', 'technology', 3500);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Ind. C', 'board-member', 'director', 'executive', null, 10500);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Law Office', 'lawyers', 'consultant', 'executive', 'operations', 4500);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Activity', null, null, null, null, -1);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Parent-Teacher Meeting', 'parent-teacher-meeting', 'meeting', 'academic', 'empower', 2000);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Teacher-Student One-on-One', 'teacher-student-one-on-one', 'meeting', 'academic', 'empower', 2000);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Teacher-Teacher Meeting', 'teacher-teacher-meeting', 'meeting', 'academic', 'empower', 2000);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Class teaching session', null, null, null, null, -1);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Class discussion session', null, null, null, null, -1);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Class presentation session', null, null, null, null, -1);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Group meeting', null, null, null, null, -1);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Group project', null, null, null, null, -1);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Acadamic day', null, null, null, null, -1);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Vacation', null, null, null, null, -1);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Holiday', null, null, null, null, -1);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Tea', null, null, null, null, -1);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Lunch', null, null, null, null, -1);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Beakfarst', null, null, null, null, -1);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Project based learning', null, null, null, null, -1);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Homeroom', null, null, null, null, -1);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Work', null, null, null, null, -1);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Prep time', null, null, null, null, -1);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Free time', null, null, null, null, -1);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Extra curricular', null, null, null, null, -1);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Teacher Foundation Meeting', null, null, null, null, -1);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Batch meeting', null, null, null, null, -1);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('School meeting', null, null, null, null, -1);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Arrival', null, null, null, null, -1);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('Departure', null, null, null, null, -1);
INSERT INTO avinya_type (description, name, global_type, foundation_type, focus, level) VALUES ('School Day', null, null, null, null, -1);
